config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  resources :spofs
  # resources :articles ,only: [:show,:index]
  resources :articles
  get "signup", to:"users#new"
  resources :users , except: [:new]
  
  root "pages#home"
  get "about", to: "pages#about"
  get "login", to: "sessions#new"
  get "user", to: "users#show"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories , except:[:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end
# start in video 2 in part 7

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase}
    before_save :encrypt_password_if_present

    has_many :articles
    
    validates :username, presence:true ,uniqueness:true,length:{minimum:3,maximum:25}

    VALID_EMAIL_REGEX = /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/

    validates :email, presence:true,uniqueness:{case_sensitive:false},  length:{minimum:3,maximum:100},format:{with:VALID_EMAIL_REGEX}

    validates :password, presence: true, length: { minimum: 8, maximum: 100 }, on: :create
    validates :password, length: { minimum: 8, maximum: 100 }, allow_blank: true, on: :update



    private

        def encrypt_password_if_present
            if will_save_change_to_password? && password.present?
                self.password = BCrypt::Password.create(password)
            end
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_same_user, only: %i[ edit update destroy ]

  # GET /Users or /Users.json
  def index
    @users = User.all
  end

  # GET /Users/1 or /Users/1.json
  def show
  end

  # GET /Users/new
  def new
    @user = User.new
  end

  # GET /Users/1/edit
  def edit
  end

  # POST /Users or /Users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to articles_path, notice: "Welcome in PODAWEP #{@user.username} ,User was successfully created." }
        format.json { render :show, status: :created, location: @User }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @User.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Users/1 or /Users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Users/1 or /Users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to Users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id].present?
      @user = User.find(params[:id]) 
      else
      @user = cur_user
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      permitted = [:username, :email]
      permitted << :password if params[:user].present? && params[:user][:password].present?
      params.require(:user).permit(permitted)
    end

    def require_same_user
      if cur_user != @user && !cur_user.admin
        redirect_to @user
      end
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <br>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <br>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, value:nil %>
  </div>
  <br>
  <div>
    <%= form.submit(edit ? "Update Profile" : "Sign up") %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing Profile" %>

<h1>Editing Profile</h1>

<%= render "form", user: @user ,edit:true%>

<br>

<div>
  <%= link_to "Home", root_path %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
    <strong>Articles count:</strong>
    <%= user.articles.length %>
    </p>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", signup_path %>

<p>
<%= link_to "Home page" , root_path %> |
<%= link_to "About page", about_path %>
</p>

app/views/users/new.html.erb
<% content_for :title, "Create user" %>

<h1>Sign up</h1>

<%= render "form", user: @user , edit:false %>

<br>

<div>
  <%= link_to "Go to Login", articles_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= gravatar_for @user , size:200 %>

<%= render @user %>

 <div>
    <strong>Articles</strong>
    <br>
    <% @user.articles.each do |art| %>
      <br>
      <%= render "articles/article", article: art%>
      <br>
      <div>
      <%= link_to "Edit this article", edit_article_path(art) %> |
  
      <%= button_to "Destroy this article", art, method: :delete, data: { turbo:false ,confirm: "Are you sure to delete ?" } %>
      </div>
    <% end %>
    <br>
    <br>
  </div>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to articles", articles_path %>
  <%= button_to "Destroy this user", @user, method: :delete, data: { turbo:false ,confirm: "Are you sure to delete ?" } %>
</div>