config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  resources :spofs
  # resources :articles ,only: [:show,:index]
  resources :articles
  get "signup", to:"users#new"
  resources :users , except: [:new]
  
  root "pages#home"
  get "about", to: "pages#about"
  get "login", to: "sessions#new"
  get "user", to: "users#show"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories , except:[:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end
# start in video 2 in part 7

app/views/pages/about.html.erb
<h1>This is about page</h1>
<%= link_to "Articles List", articles_path %> |
<%= link_to "Home page" , root_path %>

app/views/pages/home.html.erb
<h1>This is home page</h1>
<%= link_to "Articles List", articles_path %> |
<%= link_to "Categories List", categories_path %> |
<%= link_to "About page" , about_path %> |
<% if logged_in? %>
<%= link_to "#{cur_user.username}" , cur_user  %> |
<%= link_to "Logout" , logout_path , method: :delete %>
<% else %>
<%= link_to "Sign up" , signup_path %> |
<%= link_to "Login" , login_path %> 
<% end %>