config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  resources :spofs
  # resources :articles ,only: [:show,:index]
  resources :articles
  get "signup", to:"users#new"
  resources :users , except: [:new]
  
  root "pages#home"
  get "about", to: "pages#about"
  get "login", to: "sessions#new"
  get "user", to: "users#show"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories , except:[:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end
# start in video 2 in part 7

app/models/category.rb
class Category < ApplicationRecord
    validates :name , presence: true , length: { minimum: 3, maximum: 25}
    validates_uniqueness_of :name 
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_cate, only: %i[ show edit update destroy ]
  before_action :require_admin, except: %i[ show index ]

  # GET /spofs or /spofs.json
  def index
    @cates = Category.all
  end

  # GET /spofs/1 or /spofs/1.json
  def show
  end

  # GET /spofs/new
  def new
    @cate = Category.new
  end

  # GET /spofs/1/edit
  def edit
  end

  # POST /spofs or /spofs.json
  def create
    @cate = Category.new(cate_params)

    respond_to do |format|
      if @cate.save
        format.html { redirect_to @cate, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @cate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spofs/1 or /spofs/1.json
  def update
    respond_to do |format|
      if @cate.update(cate_params)
        format.html { redirect_to @cate, notice: "category was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @cate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spofs/1 or /spofs/1.json
  def destroy
    @cate.destroy!

    respond_to do |format|
      format.html { redirect_to spofs_path, notice: "Spof was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cate
      @cate = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def cate_params
      params.require(:category).permit(:name)
    end
    
    def require_admin
      unless logged_in?
        redirect_to login_path, alert: "Please log in first.", status: :see_other
        return
      end

      unless cur_user.admin?
        redirect_to categories_path, alert: "You must be an admin to access this page.", status: :see_other
      end
    end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id Category %>">

  <p>
    <strong>Category Name:<%= link_to "#{cate.name}", cate %></strong>
  <p/>
  <p>
    <strong>Category Articles Count:<%= cate.articles.length %></strong>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: cate) do |form| %>
  <% if cate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cate.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% cate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing catygory" %>

<h1>Editing catygory</h1>

<%= render "form", cate: @cate %>

<br>

<div>
  <%= link_to "Show this category", @cate %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="articles">
  <% @cates.each do |cate| %>
    <%= render "category", cate: cate %>
    <p>
      <%= link_to "Show this category", cate %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

<p>
<%= link_to "Home page" , root_path %> |
<%= link_to "About page", about_path %>
</p>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New article</h1>

<%= render "form", cate: @cate %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render "category", cate: @cate %>
<hr/>
<p><strong>Articles</strong></p>
<hr/>
<% @cate.articles.each do |art| %>
  <%= render "articles/article" , article:art %>
  <hr/>
<% end %>

<div>
  <%= link_to "Edit this category", edit_category_path(@cate) %> |
  <%= link_to "Back to categories", categories_path %>
  <%= button_to "Destroy this category", @cate, method: :delete, data: { turbo:false ,confirm: "Are you sure to delete ?" } %>
</div>